#!/bin/bash

docker run -it --rm -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -u $(id -u $USER):$(id -g $USER) -v /home/ikoryakovskiy/drl:/drl -v /home/ikoryakovskiy/grl:/grl dbl/tensorflow_cpu:latest /bin/bash

