FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

LABEL maintainer="Ivan Koryakovskiy <i.koryakovskiy@tudelft.nl>"

# supress keybord question by nvidia-cuda-dev: https://stackoverflow.com/questions/38165407/installing-lightdm-in-dockerfile-raises-interactive-keyboard-layout-menu
#COPY ./keyboard /etc/default/keyboard

# Pick up dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
	nano \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        python-pip \
        rsync \
        software-properties-common \
        unzip \
        g++ \
        cmake \
        git \
        libeigen3-dev \
        libgl1-mesa-dev \
        freeglut3-dev \
        libz-dev \
        libqt4-opengl-dev \
        libtinyxml-dev \
        libmuparser-dev \
        libode-dev \
        liblua5.1-dev \
        libprotoc-dev \
        protobuf-compiler \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        Pillow \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn \
        tensorflow-gpu \
        tflearn \
        pyyaml \
        && \
    python -m ipykernel.kernelspec

# Update GRL source
ADD https://api.github.com/repos/ikoryakovskiy/grl/git/refs/heads/master version.json
RUN git clone https://github.com/ikoryakovskiy/grl.git -b master; \
    cd grl; \
    mkdir qt-build; \
    cd qt-build; \
    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..; \
    make -j32

# Update CFG source
ADD https://api.github.com/repos/ikoryakovskiy/grlcfg/git/refs/heads/master version.json
RUN cd /grl/qt-build; \
    git clone https://github.com/ikoryakovskiy/grlcfg.git -b master cfg/

# Jump to default folder
WORKDIR /drl
