#!/bin/bash

docker run -it --rm -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -u $(id -u $USER):$(id -g $USER) -v /home/ivan/work/Project/Software/drl/:/drl -v /home/ivan/work/Project/Software/grl:/grl dbl/tensorflow_cpu:latest /bin/bash

