actor_lr: 0.0001
batch_size: 64
cfg: cfg/rbdl_py_walking.yaml
clip_norm: null
cores: 11
critic_l2_reg: 0.001
critic_lr: 0.001
curriculum: ''
gamma: 0.99
layer_norm: true
load_file: ddpg-balancing-5000000-1010-mp2
minibatch_size: 64
normalize_observations: false
normalize_returns: false
ou_sigma: 0.15
ou_theta: 0.2
output: ddpg-walking_after_balancing-25000000-1101-mp2
rb_load_filename: ddpg-balancing-5000000-1010-mp2
rb_max_size: 300000
rb_min_size: 20000
rb_save_filename: ''
reassess_for: ''
reward_scale: 1.0
save: true
seed: null
steps: 250000
tau: 0.001
tensorboard: false
test_interval: 30
trials: 0
