actor_lr: 0.0001
batch_size: 64
cfg: cfg/rbdl_py_balancing.yaml
clip_norm: null
cores: 11
critic_l2_reg: 0.001
critic_lr: 0.001
curriculum: ''
gamma: 0.99
layer_norm: true
load_file: ''
minibatch_size: 64
normalize_observations: false
normalize_returns: false
ou_sigma: 0.15
ou_theta: 0.2
output: ddpg-balancing-5000000-1010-mp1
rb_load_filename: ''
rb_max_size: 300000
rb_min_size: 20000
rb_save_filename: ddpg-balancing-5000000-1010-mp1
reassess_for: ''
reward_scale: 1.0
save: true
seed: null
steps: 50000
tau: 0.001
tensorboard: false
test_interval: 30
trials: 0
